"""
Configuration for the application, including model catalog and API keys.
"""

import logging
import os
from typing import Any, Dict, List

POE_API_KEY = os.getenv("POE_API_KEY")
LOCAL_API_KEY = os.getenv("LOCAL_API_KEY", "your-local-api-key")
MAX_FILE_SIZE_MB = int(os.getenv("MAX_FILE_SIZE_MB", "50"))

ALLOWED_FILE_TYPES = [
    # Text-based formats
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/json",
    "text/html",
    "text/xml",
    "application/rtf",

    # Python and other code
    "text/x-python",
    "application/x-python-code",
    "text/x-script.python",
    "application/javascript",
    "text/javascript",

    # Documents
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document", # .docx
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", # .xlsx
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation", # .pptx

    # Images
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/webp",
    "image/svg+xml",

    # Archives
    "application/zip",
    "application/x-tar",
    "application/gzip",
]

MODEL_CATALOG: Dict[str, Dict[str, Any]] = {
    # OpenAI
     "gpt-image-1": {
        "client_name": "openai-gpt-image-1",
        "poe_name": "gpt-image-1",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": True,
    },
    "gpt-4o": {
        "client_name": "openai-gpt-4o",
        "poe_name": "gpt-4o",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": True,
    },
    "gpt-4.1": {
        "client_name": "openai-gpt-4.1",
        "poe_name": "gpt-4.1",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gpt-4.1-nano": {
        "client_name": "openai-gpt-4.1-nano",
        "poe_name": "gpt-4.1-nano",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gpt-4.1-mini": {
        "client_name": "openai-gpt-4.1-mini",
        "poe_name": "gpt-4.1-mini",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "o3-mini-high": {
        "client_name": "openai-o3-mini-high",
        "poe_name": "o3-mini-high",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o3": {
        "client_name": "openai-o3",
        "poe_name": "o3",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o3-pro": {
        "client_name": "openai-o3-pro",
        "poe_name": "o3-pro",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o4-mini": {
        "client_name": "openai-o4-mini",
        "poe_name": "o4-mini",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o3-mini": {
        "client_name": "openai-o3-mini",
        "poe_name": "o3-mini",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o3-deep-research": {
        "client_name": "openai-o3-deep-research",
        "poe_name": "o3-deep-research",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o4-mini-deep-research": {
        "client_name": "openai-o4-mini-deep-research",
        "poe_name": "o4-mini-deep-research",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o1": {
        "client_name": "openai-o1",
        "poe_name": "o1",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o1-mini": {
        "client_name": "openai-o1-mini",
        "poe_name": "o1-mini",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o1-preview": {
        "client_name": "openai-o1-preview",
        "poe_name": "o1-preview",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "o1-pro": {
        "client_name": "openai-o1-pro",
        "poe_name": "o1-pro",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "gpt-4.5-preview": {
        "client_name": "openai-gpt-4.5-preview",
        "poe_name": "gpt-4.5-preview",
        "reasoning": True,
        "websearch": False,
        "accepts_images": False,
        "generates_images": False,
    },
    "gpt-4o-mini": {
        "client_name": "openai-gpt-4o-mini",
        "poe_name": "gpt-4o-mini",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "chatgpt-4o-latest": {
        "client_name": "openai-chatgpt-4o-latest",
        "poe_name": "chatgpt-4o-latest",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gpt-4o-search": {
        "client_name": "openai-gpt-4o-search",
        "poe_name": "gpt-4o-search",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gpt-4o-mini-search": {
        "client_name": "openai-gpt-4o-mini-search",
        "poe_name": "gpt-4o-mini-search",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    # Anthropic
    "claude-3.7-sonnet": {
        "client_name": "anthropic-claude-3.7-sonnet",
        "poe_name": "claude-3.7-sonnet",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-3.7-sonnet-reasoning": {
        "client_name": "anthropic-claude-3.7-sonnet-reasoning",
        "poe_name": "claude-3.7-sonnet-reasoning",
        "reasoning": True,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-3.7-sonnet-search": {
        "client_name": "anthropic-claude-3.7-sonnet-search",
        "poe_name": "claude-3.7-sonnet-search",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-opus-4": {
        "client_name": "anthropic-claude-opus-4",
        "poe_name": "claude-opus-4",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-4": {
        "client_name": "anthropic-claude-sonnet-4",
        "poe_name": "claude-sonnet-4",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-opus-4-reasoning": {
        "client_name": "anthropic-claude-opus-4-reasoning",
        "poe_name": "claude-opus-4-reasoning",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-4-reasoning": {
        "client_name": "anthropic-claude-sonnet-4-reasoning",
        "poe_name": "claude-sonnet-4-reasoning",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-3.5": {
        "client_name": "anthropic-claude-sonnet-3.5",
        "poe_name": "claude-sonnet-3.5",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-haiku-3.5": {
        "client_name": "anthropic-claude-haiku-3.5",
        "poe_name": "claude-haiku-3.5",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-opus-4-search": {
        "client_name": "anthropic-claude-opus-4-search",
        "poe_name": "claude-opus-4-search",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-4-search": {
        "client_name": "anthropic-claude-sonnet-4-search",
        "poe_name": "claude-sonnet-4-search",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-3.7-search": {
        "client_name": "anthropic-claude-sonnet-3.7-search",
        "poe_name": "claude-sonnet-3.7-search",
        "reasoning": False,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-sonnet-3.5-search": {
        "client_name": "anthropic-claude-sonnet-3.5-search",
        "poe_name": "claude-sonnet-3.5-search",
        "reasoning": False,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-haiku-3.5-search": {
        "client_name": "anthropic-claude-haiku-3.5-search",
        "poe_name": "claude-haiku-3.5-search",
        "reasoning": False,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "claude-opus-3": {
        "client_name": "anthropic-claude-opus-3",
        "poe_name": "claude-opus-3",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": True,
        "generates_images": False,
    },
    # Google
    "gemini-2.5-pro-preview": {
        "client_name": "google-gemini-2.5-pro-preview",
        "poe_name": "gemini-2.5-pro-preview",
        "reasoning": True,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.5-flash-preview": {
        "client_name": "google-gemini-2.5-flash-preview",
        "poe_name": "gemini-2.5-flash-preview",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.5-pro": {
        "client_name": "google-gemini-2.5-pro",
        "poe_name": "gemini-2.5-pro",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.5-flash": {
        "client_name": "google-gemini-2.5-flash",
        "poe_name": "gemini-2.5-flash",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.5-flash-lite-preview": {
        "client_name": "google-gemini-2.5-flash-lite-preview",
        "poe_name": "gemini-2.5-flash-lite-preview",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.0": {
        "client_name": "google-gemini-2.0",
        "poe_name": "gemini-2.0",
        "reasoning": False,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.0-flash-preview": {
        "client_name": "google-gemini-2.0-flash-preview",
        "poe_name": "gemini-2.0-flash-preview",
        "reasoning": True,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-2.0-flash": {
        "client_name": "google-gemini-2.0-flash",
        "poe_name": "gemini-2.0-flash",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-1.5-pro": {
        "client_name": "google-gemini-1.5-pro",
        "poe_name": "gemini-1.5-pro",
        "reasoning": True,
        "websearch": False,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-1.5-pro-search": {
        "client_name": "google-gemini-1.5-pro-search",
        "poe_name": "gemini-1.5-pro-search",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    "gemini-1.5-flash-search": {
        "client_name": "google-gemini-1.5-flash-search",
        "poe_name": "gemini-1.5-flash-search",
        "reasoning": True,
        "websearch": True,
        "accepts_images": True,
        "generates_images": False,
    },
    # Meta
    "llama-4-maverick": {
        "client_name": "meta-llama-4-maverick",
        "poe_name": "llama-4-maverick",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-4-scout-b10": {
        "client_name": "meta-llama-4-scout-b10",
        "poe_name": "llama-4-scout-b10",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-4-scout-t": {
        "client_name": "meta-llama-4-scout-t",
        "poe_name": "llama-4-scout-t",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-4-scout-nitro": {
        "client_name": "meta-llama-4-scout-nitro",
        "poe_name": "llama-4-scout-nitro",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-4-scout": {
        "client_name": "meta-llama-4-scout",
        "poe_name": "llama-4-scout",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-4-maverick-t": {
        "client_name": "meta-llama-4-maverick-t",
        "poe_name": "llama-4-maverick-t",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-3-70b-groq": {
        "client_name": "meta-llama-3-70b-groq",
        "poe_name": "llama-3-70b-groq",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-3.3-70b-fw": {
        "client_name": "meta-llama-3.3-70b-fw",
        "poe_name": "llama-3.3-70b-fw",
        "reasoning": True,
        "websearch": False,
        "accepts_images": False,
        "generates_images": False,
    },
    "llama-3.3-70b": {
        "client_name": "meta-llama-3.3-70b",
        "poe_name": "llama-3.3-70b",
        "reasoning": True,
        "websearch": False,
        "accepts_images": False,
        "generates_images": False,
    },
    # DeepSeek
    "deepseek-r1": {
        "client_name": "deepseek-r1",
        "poe_name": "deepseek-r1",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-r1-fw": {
        "client_name": "deepseek-r1-fw",
        "poe_name": "deepseek-r1-fw",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-r1-distill": {
        "client_name": "deepseek-r1-distill",
        "poe_name": "deepseek-r1-distill",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-r1-di": {
        "client_name": "deepseek-r1-di",
        "poe_name": "deepseek-r1-di",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-r1-turbo-di": {
        "client_name": "deepseek-r1-turbo-di",
        "poe_name": "deepseek-r1-turbo-di",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-v3": {
        "client_name": "deepseek-v3",
        "poe_name": "deepseek-v3",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "deepseek-v3-fw": {
        "client_name": "deepseek-v3-fw",
        "poe_name": "deepseek-v3-fw",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # xAi
    "grok-3-mini": {
        "client_name": "xai-grok-3-mini",
        "poe_name": "grok-3-mini",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "grok-3": {
        "client_name": "xai-grok-3",
        "poe_name": "grok-3",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "grok-4": {
        "client_name": "xai-grok-4",
        "poe_name": "grok-4",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # Perplexity
    "perplexity-sonar-rsn": {
        "client_name": "perplexity-sonar-rsn",
        "poe_name": "perplexity-sonar-rsn",
        "reasoning": True,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "perplexity-sonar-rsn-pro": {
        "client_name": "perplexity-sonar-rsn-pro",
        "poe_name": "perplexity-sonar-rsn-pro",
        "reasoning": True,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "perplexity-deep-research": {
        "client_name": "perplexity-deep-research",
        "poe_name": "perplexity-deep-research",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "perplexity-r1-1776": {
        "client_name": "perplexity-r1-1776",
        "poe_name": "perplexity-r1-1776",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "perplexity-sonar": {
        "client_name": "perplexity-sonar",
        "poe_name": "perplexity-sonar",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "perplexity-sonar-pro": {
        "client_name": "perplexity-sonar-pro",
        "poe_name": "perplexity-sonar-pro",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # Qwen
    "qwq-32b-b10": {
        "client_name": "qwen-qwq-32b-b10",
        "poe_name": "qwq-32b-b10",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwq-32b-t": {
        "client_name": "qwen-qwq-32b-t",
        "poe_name": "qwq-32b-t",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwq-32b-preview-t": {
        "client_name": "qwen-qwq-32b-preview-t",
        "poe_name": "qwq-32b-preview-t",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwen-qwq-32b": {
        "client_name": "qwen-qwq-32b",
        "poe_name": "qwen-qwq-32b",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwen3-235b-a22b-fw": {
        "client_name": "qwen3-235b-a22b-fw",
        "poe_name": "qwen3-235b-a22b-fw",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwen3-235b-a22b": {
        "client_name": "qwen3-235b-a22b",
        "poe_name": "qwen3-235b-a22b",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwen3-235b-a22b-di": {
        "client_name": "qwen3-235b-a22b-di",
        "poe_name": "qwen3-235b-a22b-di",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "qwen-3-235b-t": {
        "client_name": "qwen-3-235b-t",
        "poe_name": "qwen-3-235b-t",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # Mistral
    "mistral-medium": {
        "client_name": "mistral-medium",
        "poe_name": "mistral-medium",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "mistral-small-3.1": {
        "client_name": "mistral-small-3.1",
        "poe_name": "mistral-small-3.1",
        "reasoning": True,
        "websearch": False,
        "accepts_images": False,
        "generates_images": False,
    },
    # Inception
    "inception-mercury-coder": {
        "client_name": "inception-mercury-coder",
        "poe_name": "inception-mercury-coder",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # Research Tools
    "gpt-researcher": {
        "client_name": "gpt-researcher",
        "poe_name": "gpt-researcher",
        "reasoning": True,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # MiniMax
    "minimax-m1": {
        "client_name": "minimax-m1",
        "poe_name": "minimax-m1",
        "reasoning": True,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    # Poe Tools
    "assistant": {
        "client_name": "poe-assistant",
        "poe_name": "assistant",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "app-creator": {
        "client_name": "poe-app-creator",
        "poe_name": "app-creator",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "web-search": {
        "client_name": "poe-web-search",
        "poe_name": "web-search",
        "reasoning": False,
        "websearch": True,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
    "python": {
        "client_name": "poe-python",
        "poe_name": "python",
        "reasoning": False,
        "websearch": False,
        "native_tools": True,
        "accepts_images": False,
        "generates_images": False,
    },
}


AVAILABLE_MODELS: List[str] = list(MODEL_CATALOG.keys())
REASONING_MODELS: List[str] = [
    m for m, props in MODEL_CATALOG.items() if props.get("reasoning", False)
]


def get_poe_name_for_client(client_name: str) -> str:
    """Gets the internal Poe model name for a given client-facing model name."""
    for poe_name, props in MODEL_CATALOG.items():
        if props.get("client_name") == client_name:
            return props.get("poe_name", poe_name)
    return client_name


config_logger = logging.getLogger(__name__)

config_logger.info(
    "LOCAL_API_KEY loaded: %s...", (LOCAL_API_KEY[:10] if LOCAL_API_KEY else "None")
)

if not LOCAL_API_KEY or LOCAL_API_KEY == "your-local-api-key":
    raise ValueError("LOCAL_API_KEY environment variable must be set to a secure value.")
