services:
  poe-wrapper:
    container_name: poe-wrapper
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:${PORT:-8000}:8000"  # Only bind to localhost
    env_file:
      - ../.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../logs:/app/logs
    networks:
      - poe-network

  cloudflared:
    container_name: poe-cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - poe-network
    depends_on:
      poe-wrapper:
        condition: service_healthy

networks:
  poe-network:
    driver: bridge